server:
  port: 8082
spring:  application:    name: Zuul-Proxy  cloud:    consul:      discovery:        service-name: Zuul-Proxy
        register: true
      host: localhost
      port: 8500